[[DATABASE]]
DB_UID = "INFLUXDB_SERVER_A"
DB_SERVER = "192.168.2.136"
DB_PORT = "8086"
DB_TOKEN = "rwWlDBPLxGh6HJaoiOn-yh-bVdRmLOhSOjZITjD0W5TW_SHbSzl5_hOlFdk16t8OEVDANZlLM6RCXNDNRfa3xg=="
DB_ORG = "SYNTRAF"
DB_BUCKET = "SYNTRAF"
DB_ENGINE = "influxdb2"
DB_SERVER_USE_SSL = false

[[MESH_GROUP]]
UID = "LAB"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[SERVER_CLIENT]]
UID = "LAB1-VM"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "LAB",]

[[SERVER_CLIENT]]
UID = "LAB2-VM"
IP_ADDRESS = "10.1.0.200"
MESH_GROUP_UID_LIST = ["LAB",]
MAX_BANDWIDTH = "88K"

[SERVER_CLIENT.OVERRIDE_DST_NODE_IP]
EMBRASE = "43.1.1.1"

[SERVER_CLIENT.EXCLUDED_CLIENT_DICT]
LAB = "LAB3-VM"

[[SERVER_CLIENT]]
UID = "LAB3-VM"
IP_ADDRESS = "10.2.0.200"
MESH_GROUP_UID_LIST = ["LAB",]

[GLOBAL]
IPERF3_BINARY_PATH = "C:\\iperf3\\iperf3.exe"
IPERF3_TIME_SKEW_THRESHOLD = "300"
LOG_LEVEL = "DEBUG"
LOG_MAX_SIZE_PER_FILE_MB = "1"
LOG_FILE_TO_KEEP = "1"
WATCHDOG_CHECK_RATE = "2"

[SERVER]
SERVER = "192.168.2.171"

[CLIENT]
CLIENT_UID = "LAB1-VM"
SERVER = "192.168.2.171"
TOKEN = "md0a9suva0p@dsfjnav^0w43"
PUBLIC_KEY = "b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvw4MuhK+e4GBfClFQtrh\\nf1ULuRVkQ5RYgxsLOZR0MRvIjsF8iUlYkZTdLnVusnkhua5t/d5mopdtxkSHxaze\\nr7XiYDkjiFwKGh+hts5zR6tv8CBLjC8FbXsi1BF2MxI7G/u+FadnDXY86JywjxZZ\\n6+vw4d6uKioqq9D6LmLCXnn+aIlYLzVKOiuKAae+TOe5w6zn48An+EnNFr0xY6Tv\\nFieW6v4gvus2AzVZB5IuzWosSxMqYS1MYw7vuUTNA00LvzFhjI3r1p2MxqLouf64\\nOKEc6eY7ub+u2RADhqLZsVMOyOBKsEh4nurqbDn3j1wWl1Za/8lfKvB/wcoW7lNH\\nOwIDAQAB\\n-----END PUBLIC KEY-----\\n'"
CLIENT_X509_PRIVATE_KEY = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\certificate_control_channel_client\\private_key_client.pem"
CLIENT_X509_CERTIFICATE = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\certificate_control_channel_client\\certificate_client.pem"

[SERVER.TOKEN]
2018-01-01 = "md0a9suva0p@dsfjnav^0w43"
2019-01-01 = "md0a9suva066w43"
