[[MESH_GROUP]]
UID = "LAB"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[MESH_GROUP]]
UID = "BASIC_1"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[MESH_GROUP]]
UID = "BASIC_2"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[MESH_GROUP]]
UID = "BASIC_4"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[SERVER_CLIENT]]
UID = "LAB1-VM"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "LAB",]

[[SERVER_CLIENT]]
UID = "LAB2-VM"
IP_ADDRESS = "10.1.0.200"
MESH_GROUP_UID_LIST = [ "LAB",]
MAX_BANDWIDTH = "88K"

[SERVER_CLIENT.OVERRIDE_DST_NODE_IP]
LAB3-VM = "10.2.0.202"
[SERVER_CLIENT.EXCLUDED_CLIENT_DICT]
LAB = "LAB3-VM"
[[SERVER_CLIENT]]
UID = "LAB3-VM"
IP_ADDRESS = "10.2.0.200"
MESH_GROUP_UID_LIST = [ "LAB",]

#[[SERVER_CLIENT]]
#UID = "ST_CLIENT_2"
#IP_ADDRESS = "0.0.0.0"
#MESH_GROUP_UID_LIST = []
#
#[[SERVER_CLIENT]]
#UID = "ST_CLIENT_3"
#IP_ADDRESS = "0.0.0.0"
#MESH_GROUP_UID_LIST = [ "BASIC_1",]
#
#[[SERVER_CLIENT]]
#UID = "ST_CLIENT_5"
#IP_ADDRESS = "0.0.0.0"
#MESH_GROUP_UID_LIST = [ "BASIC_1",]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_6"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = []

[GLOBAL]
IPERF3_BINARY_PATH = "C:\\iperf3\\iperf3.exe"
IPERF3_TIME_SKEW_THRESHOLD = "300"
LOG_TO = "file"
LOG_LEVEL = "DEBUG"
LOG_MAX_SIZE_PER_FILE_MB = "10"
LOG_FILE_TO_KEEP = "1"
WATCHDOG_CHECK_RATE = "2"

[SERVER]
BIND_ADDRESS = "0.0.0.0"
PUBLIC_KEY = "b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqb16SI3pFW8zEB0Oy/Xf\\npiSp5G0lHZ7u6pxkYBVeDKGwBIKCCQfthN6WvrrdMLGSp9cCk4wEuBpZih/FIMZZ\\n+pGEurh8vkbKl3fikWp1g/uvmDP0Yw8uPVXsKMmpbtDk7gXt156otNFVJJPQbJzM\\nDt5xcrTC69CezUG/9WvaWDj2d1be8nGwr1W5FgrxE33QFm5yeDtwTTllTeDlHF8T\\njxnuKSZqsDd/45i+/Gelp+TdHYQGSQGeHGfQaP/GIH8fpPrrnzq20MTNer/141CZ\\npmXXwLbqSU9nzGlETa48JOCyD/GnXm6WLABms/1yL4MyysUFHfzPbjpIMg+/Azs9\\nawIDAQAB\\n-----END PUBLIC KEY-----\\n'"
SERVER_X509_PRIVATE_KEY = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\SERVER_X509_SELFSIGNED_DIRECTORY\\private_key_server.pem"
SERVER_X509_CERTIFICATE = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\SERVER_X509_SELFSIGNED_DIRECTORY\\certificate_server.pem"

#[CLIENT]
#CLIENT_UID = "ST_CLIENT_2"
#SERVER = "192.168.2.171"
#TOKEN = "md0a9suva0p@dsfjnav^0w43"
#PUBLIC_KEY = "b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxsldA75Si+2MUjMBmpDH\\noA8lt0NKfCSQyL3es/4GT1BNrRkpnBgxYtJF2bQyACtws3irbT4OlwSn6PkNGBuR\\nZUyatZBaYFbLBjT55gYIjisBgm49fD4f5IEXls2m2OjbeMRJ+wQ+YQOO6Xls7v3n\\n9hVAPhE1dZLicSWDernkfvS8wuud1as9SShxhYW/qKf3IByKoayivR+VQonuz3YE\\nt86qs8AF54cZLiVbRNgJYefdhl9sBzZ58rUcynJ59fMaFfjOKo0z26n+hqGawyim\\nFpcKE0fZfluIhVb41bOUwPhizEMc1+Wf07VTXVIsqfgFoqGRCHNNBdFU+pNe1QYQ\\nNwIDAQAB\\n-----END PUBLIC KEY-----\\n'"
#CLIENT_X509_PRIVATE_KEY = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\CLIENT_X509_SELFSIGNED_DIRECTORY\\private_key_client.pem"
#CLIENT_X509_CERTIFICATE = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\CLIENT_X509_SELFSIGNED_DIRECTORY\\certificate_client.pem"

[WEBUI]
PUBLIC_KEY = "b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApX/tTdoe+s6PBADt7grw\\nYZPnPreOPJgQB7+6Zm/84fxCto6W+Bttzn+mOVaNX1Ur9sJM6yVpEXbVxEZrTeD7\\n3uaZd04lbTjovt4bfnJAhAmR5w55BYmk5M9TTVaciQugXXWc14/n15D+OI75VZ0y\\nqXu9KPeicaiXTikOTpLh064UPIRE4asGDF0NWY0v8mdsgx3tCefKok7Q89+vxMTI\\nDOq6nNucdzjgI7e9i8eT+oEiZoTjq+4YEX/u1eVEBdcLQvr7j2J490pFpeI7na47\\nhQJphnXww8V0VkrPOudF3+8FWcNylf9RWa0wzYiB40vgU0sKiRC+brQQJpW+sXcT\\nuQIDAQAB\\n-----END PUBLIC KEY-----\\n'"
WEBUI_X509_PRIVATE_KEY = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\WEBUI_X509_SELFSIGNED_DIRECTORY\\private_key_webui.pem"
WEBUI_X509_CERTIFICATE = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\WEBUI_X509_SELFSIGNED_DIRECTORY\\certificate_webui.pem"

[SERVER.TOKEN]
#2018-01-01 = "111md0a9suva0p@dsfjnav^0w43"
2018-01-01 = "md0a9suva0p@dsfjnav^0w43"
2019-01-01 = "md0a9suva066w43"
