#[[DATABASE]]
#DB_UID = "INFLUXDB_SERVER_A"
#DB_SERVER = "192.168.2.80"
#DB_PORT = "8086"
#DB_TOKEN = "nZTbDzB3NTQr2OxraglcETePm9JZfDqW9Cx04O2zOkK1DUaADW43UGyNbLVLQNR53i-RcjN9X_TJpkyLUbixVw=="
#DB_ORG = "SYNTRAF"
#DB_BUCKET = "SYNTRAF"
#DB_ENGINE = "influxdb2"
#DB_SERVER_USE_SSL = false

#[[DATABASE]]
#DB_UID = "INFLUXDB_SERVER_B"
#DB_SERVER = "192.168.2.1"
#DB_PORT = "8086"
##DB_TOKEN = "rwWlDBPLxGh6HJaoiOn-yh-bVdRmLOhSOjZITjD0W5TW_SHbSzl5_hOlFdk16t8OEVDANZlLM6RCXNDNRfa3xg=="
#DB_ORG = "SYNTRAF"
#DB_BUCKET = "SYNTRAF"
#DB_ENGINE = "influxdb2"
#DB_SERVER_USE_SSL = false

[[MESH_GROUP]]
UID = "LAB"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[MESH_GROUP]]
UID = "BASIC_1"
BANDWIDTH = "10K"
DSCP = "0"
PACKET_SIZE = "218"
INTERVAL = "1"

[[SERVER_CLIENT]]
UID = "LAB1-VM"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "LAB",]

[[SERVER_CLIENT]]
UID = "LAB2-VM"
IP_ADDRESS = "10.1.0.200"
MESH_GROUP_UID_LIST = [ "LAB",]
MAX_BANDWIDTH = "88K"

[SERVER_CLIENT.OVERRIDE_DST_NODE_IP]
LAB3-VM = "10.2.0.202"
[SERVER_CLIENT.EXCLUDED_CLIENT_DICT]
LAB = "LAB3-VM"
[[SERVER_CLIENT]]
UID = "LAB3-VM"
IP_ADDRESS = "10.2.0.200"
MESH_GROUP_UID_LIST = [ "LAB",]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_2"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = []

[[SERVER_CLIENT]]
UID = "ST_CLIENT_3"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = ["BASIC_1"]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_5"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = ["BASIC_1"]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_6"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = []

[GLOBAL]
IPERF3_BINARY_PATH = "C:\\iperf3\\iperf3.exe"
IPERF3_TIME_SKEW_THRESHOLD = "300"
LOG_TO = "file"
LOG_LEVEL = "DEBUG"
LOG_MAX_SIZE_PER_FILE_MB = "10"
LOG_FILE_TO_KEEP = "1"
WATCHDOG_CHECK_RATE = "2"

[SERVER]
BIND_ADDRESS = "0.0.0.0"

[CLIENT]
CLIENT_UID = "ST_CLIENT_2"
SERVER = "192.168.2.171"
TOKEN = "md0a9suva0p@dsfjnav^0w43"
PUBLIC_KEY = "b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv86cLF2ElM620ubIvlMQ\\nj/AZkwFasBUCSaj6xib4NomHNh+DwThoawEL/Fi6kxS57OKDvZ+DwaZXKwSdTHfG\\npP5GUpDJ05jCaU2jnH/0ZrYfCDIjE/HWHAF9DffGBNjRjEh5SpAJpJPkv0VyQYd1\\ngZwYC1UVpLuPkpPY7wEh1FnGtEiLVQ/VJDr36Yev6bFUUtClI4nnhC0r5e//pWHx\\ntu8GD0QGyDevvmV8c4C3gRZ89CEdB85oBLZLKdYGfzevBSFaHwWk5OngrMQjBV45\\nIzIcGUyFIvnTmogD3HHetTPjY/QKqwI6r8cnfszpKA9AsSxjYIbTmVNpE+pwepKf\\nFQIDAQAB\\n-----END PUBLIC KEY-----\\n'"
CLIENT_X509_PRIVATE_KEY = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\certificate_control_channel_client\\private_key_client.pem"
CLIENT_X509_CERTIFICATE = "C:\\Users\\shado\\Documents\\Projets_PYTHON\\syntraf\\crypto\\certificate_control_channel_client\\certificate_client.pem"

[SERVER.TOKEN]
2018-01-01 = "md0a9suva0p@dsfjnav^0w43"
2019-01-01 = "md0a9suva066w43"
