[GLOBAL]
IPERF3_BINARY_PATH = "C:\\iperf3\\iperf3.exe"
IPERF3_TIME_SKEW_THRESHOLD = "300"

LOG_LEVEL = "DEBUG"
LOG_MAX_SIZE_PER_FILE_MB = "1"
LOG_FILE_TO_KEEP = "1"
WATCHDOG_CHECK_RATE = "2"

[[DATABASE]]
DB_UID = "INFLUXDB_SERVER_A"
DB_SERVER = "192.168.1.100"
DB_PORT = "8086"
DB_TOKEN = "rwWlDBPLxGh6HJaoiOn-yh-bVdRmLOhSOjZITjD0W5TW_SHbSzl5_hOlFdk16t8OEVDANZlLM6RCXNDNRfa3xg=="
DB_ORG = "SYNTRAF"
DB_BUCKET = "SYNTRAF"
DB_ENGINE = "influxdb2"
DB_SERVER_USE_SSL = false

[[DATABASE]]
DB_UID = "INFLUXDB_SERVER_B"
DB_SERVER = "192.168.1.101"
DB_SERVER_SSL = false
DB_PORT = "8086"
DB_TOKEN = "H7od1O0_sAIOVSjMSD1-XfGF5Cv9dqrAuC4im7hQxrxXT21ZbrbROOfD5jkythBrcnQ9AXqXi6nYrxCaHOiXxQ=="
DB_ORG = "SYNTRAF"
DB_BUCKET = "SYNTRAF"
DB_ENGINE = "influxdb2"
DB_SERVER_USE_SSL = false
DB_USE_WEB_PROXY = "http://10.0.0.1:8080"

[SERVER]
SERVER = "10.0.0.100"
TOKEN = { 2018-01-01 = "md0a9suva0p@dsfjnav^0w43", 2019-01-01 = "md0a9suva066w43" }
#SERVER_PORT = "6531"
#MESH_LISTENERS_PORT_RANGE = "15000-16000"
#SERVER_X509_SELFSIGNED_DIRECTORY = ""
#SERVER_X509_CERTIFICATE = ""
#SERVER_X509_CA_CHAIN = ""
#SERVER_X509_PRIVATE_KEY = ""
#COVARIANCE_TIMEFRAME = ""
#CLIENT_CLOSING_DELAY_WHEN_SERVER_UNREACHABLE = "10"

[[MESH_GROUP]]
UID = "LAB"
BANDWIDTH = "287.2K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[SERVER_CLIENT]]
UID = "WIN10-VM"
IP_ADDRESS = "10.0.0.200"
MESH_GROUP_UID_LIST = ["LAB"]

[[SERVER_CLIENT]]
UID = "WIN10-VM"
IP_ADDRESS = "10.1.0.200"
MESH_GROUP_UID_LIST = ["LAB"]
MAX_BANDWIDTH = "88K"
EXCLUDED_CLIENT_DICT = {LAB = "CENTOS8-VM"}

[[SERVER_CLIENT]]
UID = "CENTOS8-VM"
IP_ADDRESS = "10.2.0.200"
MESH_GROUP_UID_LIST = ["LAB"]