[[MESH_GROUP]]
UID = "TEST_PROFILE_1"
BANDWIDTH = "33K"
DSCP = "46"
PACKET_SIZE = "218"
INTERVAL = "1"

[[MESH_GROUP]]
UID = "TEST_PROFILE_2"
BANDWIDTH = "33K"
DSCP = "0"
PACKET_SIZE = "1000"
INTERVAL = "1"

[[SERVER_CLIENT]]
UID = "ST_SERVER"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = []

[[SERVER_CLIENT]]
UID = "ST_CLIENT_1"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "TEST_PROFILE_1",]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_2"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "TEST_PROFILE_1","TEST_PROFILE_2"]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_3"
IP_ADDRESS = "0.0.0.0"
MESH_GROUP_UID_LIST = [ "TEST_PROFILE_2","TEST_PROFILE_1"]

[[SERVER_CLIENT]]
UID = "ST_CLIENT_4"
IP_ADDRESS = "10.1.0.200"
MESH_GROUP_UID_LIST = [ "TEST_PROFILE_2",]
MAX_BANDWIDTH = "88K"

[SERVER_CLIENT.OVERRIDE_DST_NODE_IP]
ST_CLIENT_3 = "10.2.0.202"
[SERVER_CLIENT.EXCLUDED_CLIENT_DICT]
TEST_PROFILE_2 = "ST_CLIENT_2"

[[DATABASE]]
DB_UID = "INFLUXDB"
DB_SERVER = "10.1.1.100"
DB_PORT = "8086"
DB_TOKEN = "INSERTYOURINFLUXDBTOKENHERE!"
DB_ORG = "SYNTRAF"
DB_BUCKET = "SYNTRAF"
DB_ENGINE = "InfluxDB2"
DB_SERVER_USE_SSL = false

[CLIENT]
CLIENT_UID = "ST_SERVER"
SERVER = "127.0.0.1"
SERVER_PORT = "6531"
TOKEN = "TOKENTOAUTHENTICATESYNTRAFCLIENT"

[GLOBAL]
IPERF3_BINARY_PATH = "C:\\iperf3\\iperf3.exe"
IPERF3_TIME_SKEW_THRESHOLD = "300"
LOG_TO = "file"
LOG_LEVEL = "WARNING"
LOG_MAX_SIZE_PER_FILE_MB = "10"
LOG_FILE_TO_KEEP = "1"
WATCHDOG_CHECK_RATE = "2"

[SERVER]
BIND_ADDRESS = "0.0.0.0"

[SERVER.TOKEN]
2018-01-01 = "TOKENTOAUTHENTICATESYNTRAFCLIENT"